import './globals.css'



export const metadata = {
  title: 'Educal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#edeef3]'>
        {children}
        </body>
    </html>
  )
}
